### ISSUE TITLE
trabalho-01

### ISSUE THREAD

**Issue by fsantanna** [preussagnes/EDL#1]
Fiz alguns comentários menores diretamente nos seus commits.
Sugiro dar uma conferida geral na gramática.
Sobre o conteúdo:
* A análise comparativa está muito descritiva.
  Gostaria de ver uma análise mais crítica, por exemplo:
  Considerando as diferenças com C enumeradas no seu texto,  qual seria a implicação em termos de legibilidade, redigibilidade e expressividade das linguagens?
* Os exemplos de código também estão apenas listados, sem uma análise crítica comparando as versões.

**Comment by preussagnes** [comment]
Professor, fiz algumas modificações, levando em consideração seus norteamentos e espero que esteja adequado. Obrigada.

**Comment by fsantanna** [comment]
ok
